/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface CompanySettingsView {
  'updatedAt' : Timestamp,
  'address' : string,
}
export interface ContactInquiry {
  'id' : bigint,
  'subject' : string,
  'name' : string,
  'createdAt' : Timestamp,
  'email' : string,
  'message' : string,
}
export type RequestStatus = { 'awaitingAiApproval' : null } |
  { 'pending' : null } |
  { 'completed' : null } |
  { 'inProgress' : null } |
  { 'aiRejected' : null };
export type Role = { 'client' : null } |
  { 'owner' : null } |
  { 'staff' : null };
export interface ServiceRequestView {
  'id' : bigint,
  'aiRejectionReason' : [] | [string],
  'status' : RequestStatus,
  'serviceType' : ServiceType,
  'clientId' : UserId,
  'staffId' : [] | [UserId],
  'createdAt' : Timestamp,
  'description' : string,
  'updatedAt' : Timestamp,
  'proofStorageKey' : [] | [string],
}
export type ServiceType = { 'incomeTaxReturn' : null } |
  { 'etdsReturn' : null };
export interface StaffAccountView {
  'name' : string,
  'createdAt' : Timestamp,
  'isActive' : boolean,
  'email' : string,
  'principalId' : UserId,
}
export type Timestamp = bigint;
export type UserId = Principal;
export interface UserProfileView {
  'id' : UserId,
  'displayName' : string,
  'email' : string,
  'updatedAt' : Timestamp,
}
export interface _SERVICE {
  'assignRole' : ActorMethod<[UserId, Role], undefined>,
  'createStaff' : ActorMethod<[UserId, string, string], StaffAccountView>,
  'deactivateStaff' : ActorMethod<[UserId], [] | [StaffAccountView]>,
  'getCompanySettings' : ActorMethod<[], CompanySettingsView>,
  'getContactInquiry' : ActorMethod<[bigint], [] | [ContactInquiry]>,
  'getMyProfile' : ActorMethod<[], [] | [UserProfileView]>,
  'getMyRequests' : ActorMethod<[], Array<ServiceRequestView>>,
  'getMyRole' : ActorMethod<[], Role>,
  'getRequestById' : ActorMethod<[bigint], [] | [ServiceRequestView]>,
  'getRequestQueue' : ActorMethod<[], Array<ServiceRequestView>>,
  'listAllRequests' : ActorMethod<[], Array<ServiceRequestView>>,
  'listContactInquiries' : ActorMethod<[], Array<ContactInquiry>>,
  'listStaff' : ActorMethod<[], Array<StaffAccountView>>,
  'pickRequest' : ActorMethod<[bigint], [] | [ServiceRequestView]>,
  'runAiProofCheck' : ActorMethod<[bigint], [] | [ServiceRequestView]>,
  'submitContactInquiry' : ActorMethod<
    [string, string, string, string],
    ContactInquiry
  >,
  'submitRequest' : ActorMethod<[ServiceType, string], ServiceRequestView>,
  'triggerAiCheck' : ActorMethod<
    [bigint, boolean, [] | [string]],
    [] | [ServiceRequestView]
  >,
  'updateCompanyAddress' : ActorMethod<[string], CompanySettingsView>,
  'uploadProof' : ActorMethod<[bigint, string], [] | [ServiceRequestView]>,
  'upsertMyProfile' : ActorMethod<[string, string], UserProfileView>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];