/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserId = IDL.Principal;
export const Role = IDL.Variant({
  'client' : IDL.Null,
  'owner' : IDL.Null,
  'staff' : IDL.Null,
});
export const Timestamp = IDL.Int;
export const StaffAccountView = IDL.Record({
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'isActive' : IDL.Bool,
  'email' : IDL.Text,
  'principalId' : UserId,
});
export const CompanySettingsView = IDL.Record({
  'updatedAt' : Timestamp,
  'address' : IDL.Text,
});
export const ContactInquiry = IDL.Record({
  'id' : IDL.Nat,
  'subject' : IDL.Text,
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'email' : IDL.Text,
  'message' : IDL.Text,
});
export const UserProfileView = IDL.Record({
  'id' : UserId,
  'displayName' : IDL.Text,
  'email' : IDL.Text,
  'updatedAt' : Timestamp,
});
export const RequestStatus = IDL.Variant({
  'awaitingAiApproval' : IDL.Null,
  'pending' : IDL.Null,
  'completed' : IDL.Null,
  'inProgress' : IDL.Null,
  'aiRejected' : IDL.Null,
});
export const ServiceType = IDL.Variant({
  'incomeTaxReturn' : IDL.Null,
  'etdsReturn' : IDL.Null,
});
export const ServiceRequestView = IDL.Record({
  'id' : IDL.Nat,
  'aiRejectionReason' : IDL.Opt(IDL.Text),
  'status' : RequestStatus,
  'serviceType' : ServiceType,
  'clientId' : UserId,
  'staffId' : IDL.Opt(UserId),
  'createdAt' : Timestamp,
  'description' : IDL.Text,
  'updatedAt' : Timestamp,
  'proofStorageKey' : IDL.Opt(IDL.Text),
});

export const idlService = IDL.Service({
  'assignRole' : IDL.Func([UserId, Role], [], []),
  'createStaff' : IDL.Func(
      [UserId, IDL.Text, IDL.Text],
      [StaffAccountView],
      [],
    ),
  'deactivateStaff' : IDL.Func([UserId], [IDL.Opt(StaffAccountView)], []),
  'getCompanySettings' : IDL.Func([], [CompanySettingsView], ['query']),
  'getContactInquiry' : IDL.Func(
      [IDL.Nat],
      [IDL.Opt(ContactInquiry)],
      ['query'],
    ),
  'getMyProfile' : IDL.Func([], [IDL.Opt(UserProfileView)], ['query']),
  'getMyRequests' : IDL.Func([], [IDL.Vec(ServiceRequestView)], ['query']),
  'getMyRole' : IDL.Func([], [Role], ['query']),
  'getRequestById' : IDL.Func(
      [IDL.Nat],
      [IDL.Opt(ServiceRequestView)],
      ['query'],
    ),
  'getRequestQueue' : IDL.Func([], [IDL.Vec(ServiceRequestView)], ['query']),
  'listAllRequests' : IDL.Func([], [IDL.Vec(ServiceRequestView)], ['query']),
  'listContactInquiries' : IDL.Func([], [IDL.Vec(ContactInquiry)], ['query']),
  'listStaff' : IDL.Func([], [IDL.Vec(StaffAccountView)], ['query']),
  'pickRequest' : IDL.Func([IDL.Nat], [IDL.Opt(ServiceRequestView)], []),
  'runAiProofCheck' : IDL.Func([IDL.Nat], [IDL.Opt(ServiceRequestView)], []),
  'submitContactInquiry' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [ContactInquiry],
      [],
    ),
  'submitRequest' : IDL.Func([ServiceType, IDL.Text], [ServiceRequestView], []),
  'triggerAiCheck' : IDL.Func(
      [IDL.Nat, IDL.Bool, IDL.Opt(IDL.Text)],
      [IDL.Opt(ServiceRequestView)],
      [],
    ),
  'updateCompanyAddress' : IDL.Func([IDL.Text], [CompanySettingsView], []),
  'uploadProof' : IDL.Func(
      [IDL.Nat, IDL.Text],
      [IDL.Opt(ServiceRequestView)],
      [],
    ),
  'upsertMyProfile' : IDL.Func([IDL.Text, IDL.Text], [UserProfileView], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserId = IDL.Principal;
  const Role = IDL.Variant({
    'client' : IDL.Null,
    'owner' : IDL.Null,
    'staff' : IDL.Null,
  });
  const Timestamp = IDL.Int;
  const StaffAccountView = IDL.Record({
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'isActive' : IDL.Bool,
    'email' : IDL.Text,
    'principalId' : UserId,
  });
  const CompanySettingsView = IDL.Record({
    'updatedAt' : Timestamp,
    'address' : IDL.Text,
  });
  const ContactInquiry = IDL.Record({
    'id' : IDL.Nat,
    'subject' : IDL.Text,
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'email' : IDL.Text,
    'message' : IDL.Text,
  });
  const UserProfileView = IDL.Record({
    'id' : UserId,
    'displayName' : IDL.Text,
    'email' : IDL.Text,
    'updatedAt' : Timestamp,
  });
  const RequestStatus = IDL.Variant({
    'awaitingAiApproval' : IDL.Null,
    'pending' : IDL.Null,
    'completed' : IDL.Null,
    'inProgress' : IDL.Null,
    'aiRejected' : IDL.Null,
  });
  const ServiceType = IDL.Variant({
    'incomeTaxReturn' : IDL.Null,
    'etdsReturn' : IDL.Null,
  });
  const ServiceRequestView = IDL.Record({
    'id' : IDL.Nat,
    'aiRejectionReason' : IDL.Opt(IDL.Text),
    'status' : RequestStatus,
    'serviceType' : ServiceType,
    'clientId' : UserId,
    'staffId' : IDL.Opt(UserId),
    'createdAt' : Timestamp,
    'description' : IDL.Text,
    'updatedAt' : Timestamp,
    'proofStorageKey' : IDL.Opt(IDL.Text),
  });
  
  return IDL.Service({
    'assignRole' : IDL.Func([UserId, Role], [], []),
    'createStaff' : IDL.Func(
        [UserId, IDL.Text, IDL.Text],
        [StaffAccountView],
        [],
      ),
    'deactivateStaff' : IDL.Func([UserId], [IDL.Opt(StaffAccountView)], []),
    'getCompanySettings' : IDL.Func([], [CompanySettingsView], ['query']),
    'getContactInquiry' : IDL.Func(
        [IDL.Nat],
        [IDL.Opt(ContactInquiry)],
        ['query'],
      ),
    'getMyProfile' : IDL.Func([], [IDL.Opt(UserProfileView)], ['query']),
    'getMyRequests' : IDL.Func([], [IDL.Vec(ServiceRequestView)], ['query']),
    'getMyRole' : IDL.Func([], [Role], ['query']),
    'getRequestById' : IDL.Func(
        [IDL.Nat],
        [IDL.Opt(ServiceRequestView)],
        ['query'],
      ),
    'getRequestQueue' : IDL.Func([], [IDL.Vec(ServiceRequestView)], ['query']),
    'listAllRequests' : IDL.Func([], [IDL.Vec(ServiceRequestView)], ['query']),
    'listContactInquiries' : IDL.Func([], [IDL.Vec(ContactInquiry)], ['query']),
    'listStaff' : IDL.Func([], [IDL.Vec(StaffAccountView)], ['query']),
    'pickRequest' : IDL.Func([IDL.Nat], [IDL.Opt(ServiceRequestView)], []),
    'runAiProofCheck' : IDL.Func([IDL.Nat], [IDL.Opt(ServiceRequestView)], []),
    'submitContactInquiry' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [ContactInquiry],
        [],
      ),
    'submitRequest' : IDL.Func(
        [ServiceType, IDL.Text],
        [ServiceRequestView],
        [],
      ),
    'triggerAiCheck' : IDL.Func(
        [IDL.Nat, IDL.Bool, IDL.Opt(IDL.Text)],
        [IDL.Opt(ServiceRequestView)],
        [],
      ),
    'updateCompanyAddress' : IDL.Func([IDL.Text], [CompanySettingsView], []),
    'uploadProof' : IDL.Func(
        [IDL.Nat, IDL.Text],
        [IDL.Opt(ServiceRequestView)],
        [],
      ),
    'upsertMyProfile' : IDL.Func([IDL.Text, IDL.Text], [UserProfileView], []),
  });
};

export const init = ({ IDL }) => { return []; };