/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface StaffAccountView {
    name: string;
    createdAt: Timestamp;
    isActive: boolean;
    email: string;
    principalId: UserId;
}
export type UserId = Principal;
export type Timestamp = bigint;
export interface ServiceRequestView {
    id: bigint;
    aiRejectionReason?: string;
    status: RequestStatus;
    serviceType: ServiceType;
    clientId: UserId;
    staffId?: UserId;
    createdAt: Timestamp;
    description: string;
    updatedAt: Timestamp;
    proofStorageKey?: string;
}
export interface UserProfileView {
    id: UserId;
    displayName: string;
    email: string;
    updatedAt: Timestamp;
}
export interface CompanySettingsView {
    updatedAt: Timestamp;
    address: string;
}
export interface ContactInquiry {
    id: bigint;
    subject: string;
    name: string;
    createdAt: Timestamp;
    email: string;
    message: string;
}
export enum RequestStatus {
    awaitingAiApproval = "awaitingAiApproval",
    pending = "pending",
    completed = "completed",
    inProgress = "inProgress",
    aiRejected = "aiRejected"
}
export enum Role {
    client = "client",
    owner = "owner",
    staff = "staff"
}
export enum ServiceType {
    incomeTaxReturn = "incomeTaxReturn",
    etdsReturn = "etdsReturn"
}
export interface backendInterface {
    assignRole(target: UserId, role: Role): Promise<void>;
    createStaff(principalId: UserId, name: string, email: string): Promise<StaffAccountView>;
    deactivateStaff(principalId: UserId): Promise<StaffAccountView | null>;
    getCompanySettings(): Promise<CompanySettingsView>;
    getContactInquiry(id: bigint): Promise<ContactInquiry | null>;
    getMyProfile(): Promise<UserProfileView | null>;
    getMyRequests(): Promise<Array<ServiceRequestView>>;
    getMyRole(): Promise<Role>;
    getRequestById(requestId: bigint): Promise<ServiceRequestView | null>;
    getRequestQueue(): Promise<Array<ServiceRequestView>>;
    listAllRequests(): Promise<Array<ServiceRequestView>>;
    listContactInquiries(): Promise<Array<ContactInquiry>>;
    listStaff(): Promise<Array<StaffAccountView>>;
    pickRequest(requestId: bigint): Promise<ServiceRequestView | null>;
    runAiProofCheck(requestId: bigint): Promise<ServiceRequestView | null>;
    submitContactInquiry(name: string, email: string, subject: string, message: string): Promise<ContactInquiry>;
    submitRequest(serviceType: ServiceType, description: string): Promise<ServiceRequestView>;
    triggerAiCheck(requestId: bigint, approved: boolean, rejectionReason: string | null): Promise<ServiceRequestView | null>;
    updateCompanyAddress(address: string): Promise<CompanySettingsView>;
    uploadProof(requestId: bigint, storageKey: string): Promise<ServiceRequestView | null>;
    upsertMyProfile(displayName: string, email: string): Promise<UserProfileView>;
}
import type { ContactInquiry as _ContactInquiry, RequestStatus as _RequestStatus, Role as _Role, ServiceRequestView as _ServiceRequestView, ServiceType as _ServiceType, StaffAccountView as _StaffAccountView, Timestamp as _Timestamp, UserId as _UserId, UserProfileView as _UserProfileView } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async assignRole(arg0: UserId, arg1: Role): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignRole(arg0, to_candid_Role_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignRole(arg0, to_candid_Role_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createStaff(arg0: UserId, arg1: string, arg2: string): Promise<StaffAccountView> {
        if (this.processError) {
            try {
                const result = await this.actor.createStaff(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createStaff(arg0, arg1, arg2);
            return result;
        }
    }
    async deactivateStaff(arg0: UserId): Promise<StaffAccountView | null> {
        if (this.processError) {
            try {
                const result = await this.actor.deactivateStaff(arg0);
                return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deactivateStaff(arg0);
            return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCompanySettings(): Promise<CompanySettingsView> {
        if (this.processError) {
            try {
                const result = await this.actor.getCompanySettings();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCompanySettings();
            return result;
        }
    }
    async getContactInquiry(arg0: bigint): Promise<ContactInquiry | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getContactInquiry(arg0);
                return from_candid_opt_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getContactInquiry(arg0);
            return from_candid_opt_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyProfile(): Promise<UserProfileView | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyProfile();
                return from_candid_opt_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyProfile();
            return from_candid_opt_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyRequests(): Promise<Array<ServiceRequestView>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyRequests();
                return from_candid_vec_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyRequests();
            return from_candid_vec_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyRole(): Promise<Role> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyRole();
                return from_candid_Role_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyRole();
            return from_candid_Role_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getRequestById(arg0: bigint): Promise<ServiceRequestView | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getRequestById(arg0);
                return from_candid_opt_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRequestById(arg0);
            return from_candid_opt_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async getRequestQueue(): Promise<Array<ServiceRequestView>> {
        if (this.processError) {
            try {
                const result = await this.actor.getRequestQueue();
                return from_candid_vec_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRequestQueue();
            return from_candid_vec_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async listAllRequests(): Promise<Array<ServiceRequestView>> {
        if (this.processError) {
            try {
                const result = await this.actor.listAllRequests();
                return from_candid_vec_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listAllRequests();
            return from_candid_vec_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async listContactInquiries(): Promise<Array<ContactInquiry>> {
        if (this.processError) {
            try {
                const result = await this.actor.listContactInquiries();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listContactInquiries();
            return result;
        }
    }
    async listStaff(): Promise<Array<StaffAccountView>> {
        if (this.processError) {
            try {
                const result = await this.actor.listStaff();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listStaff();
            return result;
        }
    }
    async pickRequest(arg0: bigint): Promise<ServiceRequestView | null> {
        if (this.processError) {
            try {
                const result = await this.actor.pickRequest(arg0);
                return from_candid_opt_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.pickRequest(arg0);
            return from_candid_opt_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async runAiProofCheck(arg0: bigint): Promise<ServiceRequestView | null> {
        if (this.processError) {
            try {
                const result = await this.actor.runAiProofCheck(arg0);
                return from_candid_opt_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.runAiProofCheck(arg0);
            return from_candid_opt_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async submitContactInquiry(arg0: string, arg1: string, arg2: string, arg3: string): Promise<ContactInquiry> {
        if (this.processError) {
            try {
                const result = await this.actor.submitContactInquiry(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitContactInquiry(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async submitRequest(arg0: ServiceType, arg1: string): Promise<ServiceRequestView> {
        if (this.processError) {
            try {
                const result = await this.actor.submitRequest(to_candid_ServiceType_n18(this._uploadFile, this._downloadFile, arg0), arg1);
                return from_candid_ServiceRequestView_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitRequest(to_candid_ServiceType_n18(this._uploadFile, this._downloadFile, arg0), arg1);
            return from_candid_ServiceRequestView_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async triggerAiCheck(arg0: bigint, arg1: boolean, arg2: string | null): Promise<ServiceRequestView | null> {
        if (this.processError) {
            try {
                const result = await this.actor.triggerAiCheck(arg0, arg1, to_candid_opt_n20(this._uploadFile, this._downloadFile, arg2));
                return from_candid_opt_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.triggerAiCheck(arg0, arg1, to_candid_opt_n20(this._uploadFile, this._downloadFile, arg2));
            return from_candid_opt_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateCompanyAddress(arg0: string): Promise<CompanySettingsView> {
        if (this.processError) {
            try {
                const result = await this.actor.updateCompanyAddress(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateCompanyAddress(arg0);
            return result;
        }
    }
    async uploadProof(arg0: bigint, arg1: string): Promise<ServiceRequestView | null> {
        if (this.processError) {
            try {
                const result = await this.actor.uploadProof(arg0, arg1);
                return from_candid_opt_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.uploadProof(arg0, arg1);
            return from_candid_opt_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async upsertMyProfile(arg0: string, arg1: string): Promise<UserProfileView> {
        if (this.processError) {
            try {
                const result = await this.actor.upsertMyProfile(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.upsertMyProfile(arg0, arg1);
            return result;
        }
    }
}
function from_candid_RequestStatus_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _RequestStatus): RequestStatus {
    return from_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function from_candid_Role_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Role): Role {
    return from_candid_variant_n16(_uploadFile, _downloadFile, value);
}
function from_candid_ServiceRequestView_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ServiceRequestView): ServiceRequestView {
    return from_candid_record_n8(_uploadFile, _downloadFile, value);
}
function from_candid_ServiceType_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ServiceType): ServiceType {
    return from_candid_variant_n13(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserId]): UserId | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ServiceRequestView]): ServiceRequestView | null {
    return value.length === 0 ? null : from_candid_ServiceRequestView_n7(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_StaffAccountView]): StaffAccountView | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ContactInquiry]): ContactInquiry | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfileView]): UserProfileView | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    aiRejectionReason: [] | [string];
    status: _RequestStatus;
    serviceType: _ServiceType;
    clientId: _UserId;
    staffId: [] | [_UserId];
    createdAt: _Timestamp;
    description: string;
    updatedAt: _Timestamp;
    proofStorageKey: [] | [string];
}): {
    id: bigint;
    aiRejectionReason?: string;
    status: RequestStatus;
    serviceType: ServiceType;
    clientId: UserId;
    staffId?: UserId;
    createdAt: Timestamp;
    description: string;
    updatedAt: Timestamp;
    proofStorageKey?: string;
} {
    return {
        id: value.id,
        aiRejectionReason: record_opt_to_undefined(from_candid_opt_n9(_uploadFile, _downloadFile, value.aiRejectionReason)),
        status: from_candid_RequestStatus_n10(_uploadFile, _downloadFile, value.status),
        serviceType: from_candid_ServiceType_n12(_uploadFile, _downloadFile, value.serviceType),
        clientId: value.clientId,
        staffId: record_opt_to_undefined(from_candid_opt_n14(_uploadFile, _downloadFile, value.staffId)),
        createdAt: value.createdAt,
        description: value.description,
        updatedAt: value.updatedAt,
        proofStorageKey: record_opt_to_undefined(from_candid_opt_n9(_uploadFile, _downloadFile, value.proofStorageKey))
    };
}
function from_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    awaitingAiApproval: null;
} | {
    pending: null;
} | {
    completed: null;
} | {
    inProgress: null;
} | {
    aiRejected: null;
}): RequestStatus {
    return "awaitingAiApproval" in value ? RequestStatus.awaitingAiApproval : "pending" in value ? RequestStatus.pending : "completed" in value ? RequestStatus.completed : "inProgress" in value ? RequestStatus.inProgress : "aiRejected" in value ? RequestStatus.aiRejected : value;
}
function from_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    incomeTaxReturn: null;
} | {
    etdsReturn: null;
}): ServiceType {
    return "incomeTaxReturn" in value ? ServiceType.incomeTaxReturn : "etdsReturn" in value ? ServiceType.etdsReturn : value;
}
function from_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    client: null;
} | {
    owner: null;
} | {
    staff: null;
}): Role {
    return "client" in value ? Role.client : "owner" in value ? Role.owner : "staff" in value ? Role.staff : value;
}
function from_candid_vec_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ServiceRequestView>): Array<ServiceRequestView> {
    return value.map((x)=>from_candid_ServiceRequestView_n7(_uploadFile, _downloadFile, x));
}
function to_candid_Role_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Role): _Role {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_ServiceType_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ServiceType): _ServiceType {
    return to_candid_variant_n19(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_variant_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ServiceType): {
    incomeTaxReturn: null;
} | {
    etdsReturn: null;
} {
    return value == ServiceType.incomeTaxReturn ? {
        incomeTaxReturn: null
    } : value == ServiceType.etdsReturn ? {
        etdsReturn: null
    } : value;
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Role): {
    client: null;
} | {
    owner: null;
} | {
    staff: null;
} {
    return value == Role.client ? {
        client: null
    } : value == Role.owner ? {
        owner: null
    } : value == Role.staff ? {
        staff: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
